### ISSUE TITLE
asyncio_mqtt.error.MqttConnectError: [code:3] Invalid function arguments provided.

### ISSUE THREAD

**Issue by Hossein-Gholami** [sbtinstruments/aiomqtt#207] opened 2023-04-24 08:24 UTC
Hi there. I'm trying to publish a message but I get this error.
```
self.client_args = dict(
    hostname=self.mqtt_url,
    port=1883,
    username='server',
    password='server_dashboard',
    keepalive=60,
)

async with aiomqtt.Client(**self.client_args) as client:
    await client.publish(topic, payload)
```
when trying to instantiate client I get the error: 'asyncio_mqtt.error.MqttConnectError: [code:3] Invalid function arguments provided.'

version of asycio-mqtt: 0.16.1

**Comment by JonathanPlasse** [comment] 2023-04-27 17:04
Hi,
I cannot reproduce your error with the code you provided.
Can you provide a minimum working code that reproduces the error?

**Comment by empicano** [comment] 2023-08-22 20:00
Hi there 🙂 I'll close this as there have been no more responses. If this is still a problem, please feel free to reopen!

**Closed by empicano** 2023-08-22 20:00 UTC
