### ISSUE TITLE
`filtered_messages` ends up with an `Unknown` return type

### ISSUE THREAD

**Issue by sdwilsh** [sbtinstruments/aiomqtt#100] opened 2022-01-11 03:40 UTC
I think this is because of the `# type: ignore` comment when we `import paho.mqtt.client as mqtt  # type: ignore` in `client.py`, but having a hard time proving that out because `vscode` is perfectly fine with the typing, but pyright called directly isn't.

I have some code that looks like this:
```python
async with mqtt_client.filtered_messages(
    self._config.mqtt.home_assistant.birth_message.topic
) as messages:
  async for message in messages:
    pass
```

pyright complains with an error like this:
```
/home/sdwilsh/brultech-serial2mqtt/brultech_serial2mqtt/__init__.py
  /home/sdwilsh/brultech-serial2mqtt/brultech_serial2mqtt/__init__.py:158:22 - error: Type of "messages" is partially unknown
    Type of "messages" is "AsyncGenerator[Unknown, None]" (reportUnknownVariableType)
  /home/sdwilsh/brultech-serial2mqtt/brultech_serial2mqtt/__init__.py:163:31 - error: Type of "message" is unknown (reportUnknownVariableType)
2 errors, 0 warnings, 0 infos
```
The first error is the `async with`, and the second is the `async for`

**Comment by frederikaalund** [comment] 2022-01-11 08:19
Thanks for opening this issue. Let me have a look. :)

We define `filtered_messages` like this:

```python
    @asynccontextmanager
    async def filtered_messages(
        self, topic_filter: str, *, queue_maxsize: int = 0
    ) -> AsyncIterator[AsyncGenerator[mqtt.MQTTMessage, None]]:
        ...
```

So I don't think it's about the `import paho.mqtt.client as mqtt # type: ignore` at import. I'm guessing that pyright simply doesn't support this quite complex function type (both `@asynccontextmanager` and `AsyncIterator[AsyncGenerator[...]]`). It's just a guess, though.

Call to action: Try to isolate this issue in short example code that doesn't use asyncio-mqtt. If possible, we can forward the issue to the pyright devs. If not, we take a closer look at asyncio-mqtt.

Side note: [pyright does support @asynccontextmanager](https://github.com/microsoft/pyright/issues/2214#issuecomment-903134305). At least on paper.

~Frederik

**Comment by frederikaalund** [comment] 2022-01-11 08:24
Actually, it may be that you hit this code path:

https://github.com/sbtinstruments/asyncio-mqtt/blob/2a352ba87c35d4c4ee22fa4420823828e1fff025/asyncio_mqtt/client.py#L38

So you get a `# type: ignore` for Python <3.7. Which version of python do you use with pyright?

**Comment by sdwilsh** [comment] 2022-01-11 15:57
I'm running with Python 3.9, so I don't think that's it.

**Comment by frederikaalund** [comment] 2022-01-16 09:39
> I'm running with Python 3.9, so I don't think that's it.

Hmm, well then we need to investigate further. I propose that we try to isolate the issue in question. That is, remove code until we got a simple code that reproduces the issue. If it's an upstream issue (in pyright), we'll need this for the bug report. If the simplification shows us that the issue is in asyncio-mqtt, we solve it here in a PR.

Again, call to action: Anyone with time for this, please come forward. :)

**Comment by empicano** [comment] 2024-01-19 01:42
In 2.0.0 we removed `filtered_messages()`, `unfiltered_messages()`, and their successor `messages()` in favor of a single client-wide queue that's accessible via the `client.messages` generator. `client.messages` has the simpler type `AsyncGenerator[aiomqtt.Message, None]`.

I hope you're ok with closing this issue as `filtered_messages()` was removed from aiomqtt in 2.0.0, even though we never fixed this issue in the lower versions. If there's anything left unclear (or the issue persists with the new `client.messages`), please reopen!

**Closed by empicano** 2024-01-19 01:42 UTC
